BEGIN;

INSERT INTO object_types
    (key, display_name, category, geometry_dash_object_id, y_offset,
     rotation_mode, can_scale, has_color_settings, has_duration_setting, asset_path)
VALUES
    ('block', 'Block', 'block', 1, 0, 'quarter_turns', true, false, false, '/assets/objects/blocks/block.png'),
    ('line_block', 'Line block', 'block', 2, 0, 'quarter_turns', true, false, false, '/assets/objects/blocks/block-line.png'),
    ('corner_block', 'Corner block', 'block', 3, 0, 'quarter_turns', true, false, false, '/assets/objects/blocks/block-corner.png'),
    ('dot_block', 'Dot block', 'block', 4, 0, 'quarter_turns', true, false, false, '/assets/objects/blocks/block-dot.png'),
    ('deco_block', 'Decoration block', 'decoration', 5, 0, 'quarter_turns', true, false, false, '/assets/objects/blocks/block-decoration.png'),
    ('top_block', 'Top block', 'block', 6, 0, 'quarter_turns', true, false, false, '/assets/objects/blocks/block-top.png'),
    ('column_block', 'Column block', 'block', 7, 0, 'quarter_turns', true, false, false, '/assets/objects/blocks/block-column.png'),
    ('spike', 'Spike', 'hazard', 8, 0, 'free', true, false, false, '/assets/objects/hazards/spike.png'),
    ('ground_spike', 'Ground spike', 'hazard', 9, -12.5, 'free', true, false, false, '/assets/objects/hazards/spike-ground.png'),
    ('blue_portal', 'Blue gravity portal', 'portal', 10, 0, 'free', true, false, false, '/assets/objects/portals/portal-gravity-normal.png'),
    ('yellow_portal', 'Yellow gravity portal', 'portal', 11, 0, 'free', true, false, false, '/assets/objects/portals/portal-gravity-reversed.png'),
    ('cube_portal', 'Cube portal', 'portal', 12, 0, 'free', true, false, false, '/assets/objects/portals/portal-cube.png'),
    ('ship_portal', 'Ship portal', 'portal', 13, 0, 'free', true, false, false, '/assets/objects/portals/portal-ship.png'),
    ('ball_portal', 'Ball portal', 'portal', NULL, 0, 'free', true, false, false, '/assets/objects/portals/portal-ball.png'),
    ('ufo_portal', 'UFO portal', 'portal', NULL, 0, 'free', true, false, false, '/assets/objects/portals/portal-ufo.png'),
    ('wave_portal', 'Wave portal', 'portal', NULL, 0, 'free', true, false, false, '/assets/objects/portals/portal-wave.png'),
    ('robot_portal', 'Robot portal', 'portal', NULL, 0, 'free', true, false, false, '/assets/objects/portals/portal-robot.png'),
    ('spider_portal', 'Spider portal', 'portal', NULL, 0, 'free', true, false, false, '/assets/objects/portals/portal-spider.png'),
    ('swing_portal', 'Swing portal', 'portal', NULL, 0, 'free', true, false, false, '/assets/objects/portals/portal-swing.png'),
    ('mini_portal', 'Mini portal', 'portal', NULL, 0, 'free', true, false, false, '/assets/objects/portals/portal-size-mini.png'),
    ('normal_size_portal', 'Normal-size portal', 'portal', NULL, 0, 'free', true, false, false, '/assets/objects/portals/portal-size-normal.png'),
    ('yellow_pad', 'Yellow jump pad', 'pad', 35, -13, 'free', true, false, false, '/assets/objects/pads/pad-jump-yellow.png'),
    ('pink_pad', 'Pink jump pad', 'pad', NULL, -13, 'free', true, false, false, '/assets/objects/pads/pad-jump-pink.png'),
    ('red_pad', 'Red jump pad', 'pad', NULL, -13, 'free', true, false, false, '/assets/objects/pads/pad-jump-red.png'),
    ('blue_gravity_pad', 'Blue gravity pad', 'pad', NULL, -13, 'free', true, false, false, '/assets/objects/pads/pad-gravity-blue.png'),
    ('purple_spider_pad', 'Purple spider pad', 'pad', NULL, -13, 'free', true, false, false, '/assets/objects/pads/pad-spider-purple.png'),
    ('yellow_orb', 'Yellow jump orb', 'orb', 36, 0, 'free', true, false, false, '/assets/objects/orbs/orb-jump-yellow.png'),
    ('pink_orb', 'Pink jump orb', 'orb', NULL, 0, 'free', true, false, false, '/assets/objects/orbs/orb-jump-pink.png'),
    ('red_orb', 'Red jump orb', 'orb', NULL, 0, 'free', true, false, false, '/assets/objects/orbs/orb-jump-red.png'),
    ('blue_gravity_orb', 'Blue gravity orb', 'orb', NULL, 0, 'free', true, false, false, '/assets/objects/orbs/orb-gravity-blue.png'),
    ('green_gravity_orb', 'Green gravity orb', 'orb', NULL, 0, 'free', true, false, false, '/assets/objects/orbs/orb-gravity-green.png'),
    ('black_orb', 'Black orb', 'orb', NULL, 0, 'free', true, false, false, '/assets/objects/orbs/orb-drop-black.png'),
    ('green_dash_orb', 'Green dash orb', 'orb', NULL, 0, 'free', true, false, false, '/assets/objects/orbs/orb-dash-green.png'),
    ('pink_dash_orb', 'Pink dash orb', 'orb', NULL, 0, 'free', true, false, false, '/assets/objects/orbs/orb-dash-pink.png'),
    ('purple_spider_orb', 'Purple spider orb', 'orb', NULL, 0, 'free', true, false, false, '/assets/objects/orbs/orb-spider-purple.png'),
    ('slow_speed', 'Slow speed', 'speed', NULL, 0, 'free', true, false, false, '/assets/objects/speeds/speed-slow.png'),
    ('normal_speed', 'Normal speed', 'speed', NULL, 0, 'free', true, false, false, '/assets/objects/speeds/speed-normal.png'),
    ('fast_speed', 'Fast speed', 'speed', NULL, 0, 'free', true, false, false, '/assets/objects/speeds/speed-fast.png'),
    ('very_fast_speed', 'Very fast speed', 'speed', NULL, 0, 'free', true, false, false, '/assets/objects/speeds/speed-very-fast.png'),
    ('extremely_fast_speed', 'Extremely fast speed', 'speed', NULL, 0, 'free', true, false, false, '/assets/objects/speeds/speed-extremely-fast.png'),
    ('flat_spike', 'Flat spike', 'hazard', 39, -9, 'free', true, false, false, '/assets/objects/hazards/spike-flat.png'),
    ('half_block', 'Half block', 'block', 40, 8, 'quarter_turns', true, false, false, '/assets/objects/blocks/block-half.png'),
    ('bg_color_trigger', 'Background color trigger', 'trigger', 899, 0, 'none', false, true, true, '/assets/objects/triggers/trigger-color.png'),
    ('g1_color_trigger', 'Ground color trigger', 'trigger', 899, 0, 'none', false, true, true, '/assets/objects/triggers/trigger-color.png')
ON CONFLICT (key) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    category = EXCLUDED.category,
    geometry_dash_object_id = COALESCE(EXCLUDED.geometry_dash_object_id, object_types.geometry_dash_object_id),
    y_offset = EXCLUDED.y_offset,
    rotation_mode = EXCLUDED.rotation_mode,
    can_scale = EXCLUDED.can_scale,
    has_color_settings = EXCLUDED.has_color_settings,
    has_duration_setting = EXCLUDED.has_duration_setting,
    asset_path = EXCLUDED.asset_path,
    is_active = true;

COMMIT;
